# Creaza resource pools	
---
- hosts: localhost
  connection: local
  tasks:
    - name: include vars
      include_vars:
        dir: group_vars

# Creeaza Folderul in care va sta toate vm-urile de la curs
    - name: Create Dev Laborator - "Dev-Atac-DDos"
      vcenter_folder:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter_name: "{{ datacenter }}"
        validate_certs: no
        folder_name: "{{ default_name_folder }}{{ dev_folder }}"
        folder_type: vm
        state: "{{ status_folder }}"
#       delegate_to: localhost  	

# Ceeaza Resource Pools pentru studentii de la curs
    - name: Creaza Resource Pools
      vmware_resource_pool:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username}}"
        password: "{{ vcenter_password}}"
        validate_certs: False
        state: "{{ status_rp }}"
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster }}"
        cpu_limit: 2000
        mem_limit: 2048
        resource_pool: "{{ rp_laborator_prefix }}{{ item }}"
      with_items: "{{ with_items_vm_rp }} "

# Creeaza vm linux pentru template si converteste vm in template  
# Pas 1    
    - name: Creeaza din template VM pentru configurat 
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username}}"
        password: "{{ vcenter_password}}"
        datacenter: "{{ datacenter }}"
        validate_certs: no
        state: "{{ status_vm_on }}"
#       force: yes
        name: "{{ centos7_template }}"
        template: "{{ template_CentOS7 }}"
        folder: "{{ default_name_folder }}{{ dev_folder }}"
        hardware:
          num_cpu: "{{ num_cpu_centos7_v01 }}"
          memory_mb: "{{ memory_mb_centos7_v01 }}"
        networks:
          - name: "{{ network_vm_network }}"
            mac: "{{ vcsa_mac }}{{ vm_mac }}"
#           start_connected: yes
            type: static
            ip: "{{ clasa_adresa_ip }}.{{ adresa_ip_centos7_User_XX }}{{ item }}" # comentata - creeaza erori de deploy
            netmask: "{{ netmask_centos7 }}"
            gateway: "{{ clasa_adresa_ip }}.{{ gateway_centos7 }}"
        wait_for_customization: "{{ asteapta_modificari_vm }}"
      with_items:  "{{ with_items_vm_rp }} "
# Pas 2
    - name: Opreste VM pentru convertire template linux
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username}}"
        password: "{{ vcenter_password}}"
        datacenter: "{{ datacenter }}"
        validate_certs: no
        state: "{{ status_vm_off }}"
        name: "{{ centos7_template }}"
#       force: yes
        folder: "{{ default_name_folder }}{{ dev_folder }}"
        state_change_timeout: "{{ asteapta_status_vm }}"

# Pas 3
    - name: Convertire in template linux
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username}}"
        password: "{{ vcenter_password}}"
        datacenter: "{{ datacenter }}"
        validate_certs: no
#        state: poweredoff
#        force: yes
        name: "{{ centos7_template }}"
        is_template: yes
        wait_for_customization: "{{ asteapta_modificari_vm }}"
        




















