---
# List Template content
- hosts: localhost
  connection: local
  tasks:
    - name: include vars
      include_vars:
        dir: group_vars
    
    - name: Gather facts from standalone ESXi server having datacenter as 'ha-datacenter'
      vmware_guest_facts:
            hostname: '{{ vcenter_ip }}'
            username: '{{ vcenter_username }}'
            password: '{{ vcenter_password }}'
            datacenter: '{{ datacenter }}'
            folder: /Template-Area
            validate_certs: no
            name: "{{ item }}"
            name_match: first
#            uuid: 421e4592-c069-924d-ce20-7e7533fab926
#      delegate_to: localhost
      register: facts
      with_items :
      - Template-w7-test
      - programare