---
- name: Create a VM from a template - linux
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: include vars
    include_vars:
      dir: group_vars
      
  - name: Clone the template 
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username}}"
      password: "{{ vcenter_password}}"
      datacenter: "{{ datacenter }}"
      validate_certs: no
      state: poweredon
#      force: yes
      name: "VM_{{ item }}"
      template: "{{ template_CentOS7 }}"
      resource_pool: "Laborator_{{ item }}"
      folder: "/Laborator_{{ item }}"
      hardware:
        num_cpu: "{{ num_cpu_centos7_v01 }}"
        memory_mb: "{{ memory_mb_centos7_v01 }}"
      networks:
        - name: "{{ network_vm_network }}"
          mac: "{{ vcsa_mac }}{{ vm_mac }}"
#          start_connected: yes
          type: static
          ip: "{{ clasa_adresa_ip }}.{{ adresa_ip_centos7_User_XX }}{{ item }}"
          netmask: "{{ netmask_centos7 }}"
          gateway: "{{ clasa_adresa_ip }}.{{ gateway_centos7 }}"
      wait_for_ip_address: yes
#      is_template: yes
    with_items :
    - "02" 

  - name: PowerOff VM ! Stage 1
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username}}"
      password: "{{ vcenter_password}}"
      datacenter: "{{ datacenter }}"
      validate_certs: no
      state: poweredoff
#      force: yes
      name: "VM_{{ item }}"
      template: "{{ template_CentOS7 }}"
      resource_pool: "Laborator_{{ item }}"
      folder: "/Laborator_{{ item }}"
#      is_template: yes
      state_change_timeout: 1
    with_items :
    - "02"
    
  - name: Mark vm as template !Stage 2
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username}}"
      password: "{{ vcenter_password}}"
      datacenter: "{{ datacenter }}"
      validate_certs: no
#      state: poweredoff
#      force: yes
      name: "VM_{{ item }}"
      is_template: yes
      wait_for_customization: yes
    with_items :
    - "02"       