---
# Create VM folder vcenter
- hosts: localhost
  connection: local
  tasks:
    - name: include vars
      include_vars:
        dir: group_vars
        
    - name: Create a VM folder on given datacenter
      vcenter_folder:
            hostname: '{{ vcenter_ip }}'
            username: '{{ vcenter_username }}'
            password: '{{ vcenter_password }}'
            datacenter_name: '{{ datacenter }}'
            validate_certs: no
            folder_name: sample_vm_folder
            folder_type: vm
            state: absent
#           register: vm_folder_creation_result
#           delegate_to: localhost     